2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Configure stats pid to 54181
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Loading settings from /Users/adamimos/.config/wandb/settings
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Loading settings from /Users/adamimos/Documents/GitHub/epsilon-transformers/wandb/settings
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_init.py:_log_setup():524] Logging user logs to /Users/adamimos/Documents/GitHub/epsilon-transformers/wandb/run-20240118_162643-gp20n2u9/logs/debug.log
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/adamimos/Documents/GitHub/epsilon-transformers/wandb/run-20240118_162643-gp20n2u9/logs/debug-internal.log
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_init.py:init():564] calling init triggers
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'train': {'batch_size': 64, 'sequence_length': 500, 'num_sequences': 100, 'num_epochs': 200, 'learning_rate': 0.00015, 'weight_decay': 0}, 'model': {'n_layers': 2, 'd_model': 16, 'n_ctx': 10, 'd_head': 4, 'model_name': 'custom', 'n_heads': 4, 'd_mlp': 64, 'act_fn': 'relu', 'd_vocab': 2, 'eps': 1e-05, 'use_attn_result': False, 'use_attn_scale': True, 'use_split_qkv_input': False, 'use_hook_mlp_in': False, 'use_attn_in': False, 'use_local_attn': False, 'original_architecture': None, 'from_checkpoint': False, 'checkpoint_index': None, 'checkpoint_label_type': None, 'checkpoint_value': None, 'tokenizer_name': None, 'window_size': None, 'attn_types': None, 'init_mode': 'gpt2', 'normalization_type': None, 'device': 'cpu', 'n_devices': 1, 'attention_dir': 'causal', 'attn_only': False, 'seed': 42, 'initializer_range': 0.2, 'init_weights': True, 'scale_attn_by_inverse_layer_idx': False, 'positional_embedding_type': 'standard', 'final_rms': False, 'd_vocab_out': 2, 'parallel_attn_mlp': False, 'rotary_dim': None, 'n_params': 6144, 'use_hook_tokens': False, 'gated_mlp': False, 'default_prepend_bos': True, 'dtype': torch.float32, 'tokenizer_prepends_bos': None, 'post_embedding_ln': False}}
2024-01-18 16:26:43,878 INFO    MainThread:54181 [wandb_init.py:init():589] re-initializing run, found existing run on stack: hi2abrf6
2024-01-18 16:26:43,879 INFO    MainThread:54181 [wandb_run.py:_finish():1962] finishing run adamimos/epsilon-transformers/hi2abrf6
2024-01-18 16:26:43,879 INFO    MainThread:54181 [jupyter.py:save_history():445] not saving jupyter history
2024-01-18 16:26:43,879 INFO    MainThread:54181 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-01-18 16:26:43,879 INFO    MainThread:54181 [wandb_init.py:_jupyter_teardown():452] cleaning up jupyter logic
2024-01-18 16:26:43,879 INFO    MainThread:54181 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-18 16:26:43,879 INFO    MainThread:54181 [wandb_run.py:_restore():2185] restore
2024-01-18 16:26:43,880 INFO    MainThread:54181 [wandb_run.py:_restore():2191] restore done
2024-01-18 16:26:50,531 INFO    MainThread:54181 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-18 16:26:50,532 INFO    MainThread:54181 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-18 16:26:50,538 INFO    MainThread:54181 [wandb_run.py:_footer_sync_info():3796] logging synced files
2024-01-18 16:26:50,616 INFO    MainThread:54181 [wandb_init.py:init():614] starting backend
2024-01-18 16:26:50,616 INFO    MainThread:54181 [wandb_init.py:init():618] setting up manager
2024-01-18 16:26:50,617 INFO    MainThread:54181 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-18 16:26:50,617 INFO    MainThread:54181 [wandb_init.py:init():624] backend started and connected
2024-01-18 16:26:50,621 INFO    MainThread:54181 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-18 16:26:50,621 INFO    MainThread:54181 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-18 16:26:50,621 INFO    MainThread:54181 [wandb_init.py:init():716] updated telemetry
2024-01-18 16:26:50,638 INFO    MainThread:54181 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-18 16:26:51,790 INFO    MainThread:54181 [wandb_run.py:_on_init():2254] communicating current version
2024-01-18 16:26:51,832 INFO    MainThread:54181 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.2 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-01-18 16:26:51,832 INFO    MainThread:54181 [wandb_init.py:init():800] starting run threads in backend
2024-01-18 16:26:54,739 INFO    MainThread:54181 [wandb_run.py:_console_start():2233] atexit reg
2024-01-18 16:26:54,739 INFO    MainThread:54181 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-01-18 16:26:54,740 INFO    MainThread:54181 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-01-18 16:26:54,740 INFO    MainThread:54181 [wandb_run.py:_redirect():2178] Redirects installed.
2024-01-18 16:26:54,740 INFO    MainThread:54181 [wandb_init.py:init():841] run started, returning control to user process
2024-01-18 16:41:05,929 INFO    MainThread:54181 [wandb_run.py:_finish():1962] finishing run adamimos/epsilon-transformers/gp20n2u9
2024-01-18 16:41:05,930 INFO    MainThread:54181 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-01-18 16:41:05,930 INFO    MainThread:54181 [wandb_run.py:_restore():2185] restore
2024-01-18 16:41:05,930 INFO    MainThread:54181 [wandb_run.py:_restore():2191] restore done
2024-01-18 16:41:11,572 INFO    MainThread:54181 [wandb_run.py:_footer_history_summary_info():3837] rendering history
2024-01-18 16:41:11,573 INFO    MainThread:54181 [wandb_run.py:_footer_history_summary_info():3869] rendering summary
2024-01-18 16:41:11,576 INFO    MainThread:54181 [wandb_run.py:_footer_sync_info():3796] logging synced files
