2024-01-18 16:21:14,162 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2024-01-18 16:21:14,162 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Configure stats pid to 53973
2024-01-18 16:21:14,162 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Loading settings from /Users/adamimos/.config/wandb/settings
2024-01-18 16:21:14,162 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Loading settings from /Users/adamimos/Documents/GitHub/epsilon-transformers/wandb/settings
2024-01-18 16:21:14,162 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_init.py:_log_setup():524] Logging user logs to /Users/adamimos/Documents/GitHub/epsilon-transformers/wandb/run-20240118_162114-809o1ndt/logs/debug.log
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_init.py:_log_setup():525] Logging internal logs to /Users/adamimos/Documents/GitHub/epsilon-transformers/wandb/run-20240118_162114-809o1ndt/logs/debug-internal.log
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_init.py:init():564] calling init triggers
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {'train': {'batch_size': 64, 'sequence_length': 500, 'num_sequences': 1000, 'num_epochs': 200, 'learning_rate': 0.015, 'weight_decay': 0}, 'model': {'n_layers': 2, 'd_model': 16, 'n_ctx': 10, 'd_head': 4, 'model_name': 'custom', 'n_heads': 4, 'd_mlp': 64, 'act_fn': 'relu', 'd_vocab': 2, 'eps': 1e-05, 'use_attn_result': False, 'use_attn_scale': True, 'use_split_qkv_input': False, 'use_hook_mlp_in': False, 'use_attn_in': False, 'use_local_attn': False, 'original_architecture': None, 'from_checkpoint': False, 'checkpoint_index': None, 'checkpoint_label_type': None, 'checkpoint_value': None, 'tokenizer_name': None, 'window_size': None, 'attn_types': None, 'init_mode': 'gpt2', 'normalization_type': None, 'device': 'cpu', 'n_devices': 1, 'attention_dir': 'causal', 'attn_only': False, 'seed': 42, 'initializer_range': 0.2, 'init_weights': True, 'scale_attn_by_inverse_layer_idx': False, 'positional_embedding_type': 'standard', 'final_rms': False, 'd_vocab_out': 2, 'parallel_attn_mlp': False, 'rotary_dim': None, 'n_params': 6144, 'use_hook_tokens': False, 'gated_mlp': False, 'default_prepend_bos': True, 'dtype': torch.float32, 'tokenizer_prepends_bos': None, 'post_embedding_ln': False}}
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_init.py:init():614] starting backend
2024-01-18 16:21:14,163 INFO    MainThread:53973 [wandb_init.py:init():618] setting up manager
2024-01-18 16:21:14,163 INFO    MainThread:53973 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-01-18 16:21:14,164 INFO    MainThread:53973 [wandb_init.py:init():624] backend started and connected
2024-01-18 16:21:14,170 INFO    MainThread:53973 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-01-18 16:21:14,170 INFO    MainThread:53973 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-01-18 16:21:14,170 INFO    MainThread:53973 [wandb_init.py:init():716] updated telemetry
2024-01-18 16:21:14,189 INFO    MainThread:53973 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2024-01-18 16:22:44,375 ERROR   MainThread:53973 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2024-01-18 16:22:44,444 ERROR   MainThread:53973 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "/Users/adamimos/anaconda3/envs/epsilon-machine/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "/Users/adamimos/anaconda3/envs/epsilon-machine/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
